### ISSUE TITLE
global install FR

### ISSUE THREAD

**Issue by olilarkin** [pingdynasty/OwlProgram#38] opened 2016-05-04 11:34 UTC
would be great if owlprogram could have the option to be installed globally, i.e. in /usr/local/bin so that anywhere i have an OwlPatch.hpp i can compile and output in that folder, rather than copying to patchsource. (a bit like how faust does it!)

**Comment by pingdynasty** [comment] 2016-05-04 11:42
Duplicate of #35

**Closed as completed** 2016-08-28 13:45 UTC
Labels: duplicate
